-- MySQL Script generated by MySQL Workbench
-- Tue Feb 14 21:09:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Biblioteca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Biblioteca` (
  `nomep` VARCHAR(45) NOT NULL,
  `Bibliotecacol` VARCHAR(45) NULL,
  `professor_siape` INT NOT NULL,
  `professor_quantidade de livro` INT NOT NULL,
  PRIMARY KEY (`professor_siape`, `professor_quantidade de livro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `nome` VARCHAR(45) NOT NULL,
  `siape` INT NOT NULL,
  PRIMARY KEY (`siape`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `rga` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livro` (
  `idLivro` INT NOT NULL,
  `NomeDoLivro` VARCHAR(45) NOT NULL,
  `NomeDoAutor` VARCHAR(45) NOT NULL,
  `Idioma` VARCHAR(45) NOT NULL,
  `QuantidadeDePaginas` INT NOT NULL,
  `professor_siape` VARCHAR(45) NOT NULL,
  `aluno_rga` INT NOT NULL,
  PRIMARY KEY (`idLivro`, `QuantidadeDePaginas`),
  INDEX `fk_Livro_professor1_idx` (`professor_siape` ASC),
  INDEX `fk_Livro_aluno1_idx` (`aluno_rga` ASC),
  CONSTRAINT `fk_Livro_professor1`
    FOREIGN KEY (`professor_siape`)
    REFERENCES `mydb`.`professor` (`siape`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_aluno1`
    FOREIGN KEY (`aluno_rga`)
    REFERENCES `mydb`.`aluno` (`rga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Biblioteca_has_Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Biblioteca_has_Livro` (
  `Biblioteca_professor_siape` VARCHAR(45) NOT NULL,
  `Biblioteca_professor_quantidade de livro` VARCHAR(45) NOT NULL,
  `Biblioteca_professor_siape1` VARCHAR(45) NOT NULL,
  `Livro_idLivro` INT NOT NULL,
  `Livro_QuantidadeDePaginas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Biblioteca_professor_siape`, `Biblioteca_professor_quantidade de livro`, `Biblioteca_professor_siape1`, `Livro_idLivro`, `Livro_QuantidadeDePaginas`),
  INDEX `fk_Biblioteca_has_Livro_Livro1_idx` (`Livro_idLivro` ASC, `Livro_QuantidadeDePaginas` ASC),
  INDEX `fk_Biblioteca_has_Livro_Biblioteca1_idx` (`Biblioteca_professor_siape` ASC, `Biblioteca_professor_quantidade de livro` ASC, `Biblioteca_professor_siape1` ASC),
  CONSTRAINT `fk_Biblioteca_has_Livro_Biblioteca1`
    FOREIGN KEY (`Biblioteca_professor_siape` , `Biblioteca_professor_quantidade de livro`)
    REFERENCES `mydb`.`Biblioteca` (`professor_siape` , `professor_quantidade de livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Biblioteca_has_Livro_Livro1`
    FOREIGN KEY (`Livro_idLivro` , `Livro_QuantidadeDePaginas`)
    REFERENCES `mydb`.`Livro` (`idLivro` , `QuantidadeDePaginas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `NomeDoAutor` VARCHAR(100) NOT NULL,
  `IdAutor` INT NOT NULL,
  PRIMARY KEY (`IdAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Editora` (
  `NomeDaEditora` VARCHAR(70) NOT NULL,
  `NomeDaObra` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livro_has_Editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livro_has_Editora` (
  `Livro_idLivro` INT NOT NULL,
  `Livro_QuantidadeDePaginas` VARCHAR(45) NOT NULL,
  `Editora_NomeDaEditora` INT NOT NULL,
  PRIMARY KEY (`Livro_idLivro`, `Livro_QuantidadeDePaginas`, `Editora_NomeDaEditora`),
  INDEX `fk_Livro_has_Editora_Editora1_idx` (`Editora_NomeDaEditora` ASC),
  INDEX `fk_Livro_has_Editora_Livro1_idx` (`Livro_idLivro` ASC, `Livro_QuantidadeDePaginas` ASC),
  CONSTRAINT `fk_Livro_has_Editora_Livro1`
    FOREIGN KEY (`Livro_idLivro` , `Livro_QuantidadeDePaginas`)
    REFERENCES `mydb`.`Livro` (`idLivro` , `QuantidadeDePaginas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_has_Editora_Editora1`
    FOREIGN KEY (`Editora_NomeDaEditora`)
    REFERENCES `mydb`.`Editora` (`NomeDaEditora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor_has_Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor_has_Livro` (
  `Autor_IdAutor` INT NOT NULL,
  `Livro_idLivro` INT NOT NULL,
  `Livro_QuantidadeDePaginas` INT NOT NULL,
  PRIMARY KEY (`Autor_IdAutor`, `Livro_idLivro`, `Livro_QuantidadeDePaginas`),
  INDEX `fk_Autor_has_Livro_Livro1_idx` (`Livro_idLivro` ASC, `Livro_QuantidadeDePaginas` ASC),
  INDEX `fk_Autor_has_Livro_Autor1_idx` (`Autor_IdAutor` ASC),
  CONSTRAINT `fk_Autor_has_Livro_Autor1`
    FOREIGN KEY (`Autor_IdAutor`)
    REFERENCES `mydb`.`Autor` (`IdAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_has_Livro_Livro1`
    FOREIGN KEY (`Livro_idLivro` , `Livro_QuantidadeDePaginas`)
    REFERENCES `mydb`.`Livro` (`idLivro` , `QuantidadeDePaginas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Biblioteca_has_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Biblioteca_has_aluno` (
  `Biblioteca_professor_siape` INT NOT NULL,
  `Biblioteca_professor_quantidade de livro` INT NOT NULL,
  `aluno_rga` INT NOT NULL,
  PRIMARY KEY (`Biblioteca_professor_siape`, `Biblioteca_professor_quantidade de livro`, `aluno_rga`),
  INDEX `fk_Biblioteca_has_aluno_aluno1_idx` (`aluno_rga` ASC),
  INDEX `fk_Biblioteca_has_aluno_Biblioteca1_idx` (`Biblioteca_professor_siape` ASC, `Biblioteca_professor_quantidade de livro` ASC),
  CONSTRAINT `fk_Biblioteca_has_aluno_Biblioteca1`
    FOREIGN KEY (`Biblioteca_professor_siape` , `Biblioteca_professor_quantidade de livro`)
    REFERENCES `mydb`.`Biblioteca` (`professor_siape` , `professor_quantidade de livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Biblioteca_has_aluno_aluno1`
    FOREIGN KEY (`aluno_rga`)
    REFERENCES `mydb`.`aluno` (`rga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Biblioteca_has_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Biblioteca_has_professor` (
  `Biblioteca_professor_siape` INT NOT NULL,
  `Biblioteca_professor_quantidade de livro` INT NOT NULL,
  `professor_siape` INT NOT NULL,
  PRIMARY KEY (`Biblioteca_professor_siape`, `Biblioteca_professor_quantidade de livro`, `professor_siape`),
  INDEX `fk_Biblioteca_has_professor_professor1_idx` (`professor_siape` ASC),
  INDEX `fk_Biblioteca_has_professor_Biblioteca1_idx` (`Biblioteca_professor_siape` ASC, `Biblioteca_professor_quantidade de livro` ASC),
  CONSTRAINT `fk_Biblioteca_has_professor_Biblioteca1`
    FOREIGN KEY (`Biblioteca_professor_siape` , `Biblioteca_professor_quantidade de livro`)
    REFERENCES `mydb`.`Biblioteca` (`professor_siape` , `professor_quantidade de livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Biblioteca_has_professor_professor1`
    FOREIGN KEY (`professor_siape`)
    REFERENCES `mydb`.`professor` (`siape`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
